title: "Tianwei Yin"
author: "Tianwei Yin"
description: "University of Melbourne>"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false        # show article excerpts on the home page
show_frame: false           # adds a gray frame to the site
show_sidebar: true        # show a sidebar instead of the usual header
minimal: true             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "research.md", title: Projects}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Linkedin, url: "https://www.linkedin.com/in/tianwei-yin-b057a7169/"}
  - {title: Instagram, url: "https://www.instagram.com/tianwei_yin/"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
