title: "Tianwei Yin"
author: "Tianwei Yin"
description: "University of Melbourne>"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: true        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html", title: Research}
  - {file: "README.md", title: Personal}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "tiyin@student.unimelb.edu.au"}
  - {title: Linkedin, icon: <i class="fab fa-linkedin"></i>, url: "https://www.linkedin.com/in/tianwei-yin-b057a7169/"}


comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
